services:
  - type: web
    name: mdraft-web
    env: python
    buildCommand: pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
    runtime: python-3.11.11
    preDeployCommand: |
      # Set fallback session backend for pre-deployment
      export SESSION_BACKEND="${SESSION_BACKEND:-filesystem}"
      export SESSION_TYPE="${SESSION_TYPE:-filesystem}"
      echo "Pre-deployment setup complete"
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 8 --timeout 120 --access-logfile - --error-logfile - wsgi:app
    postDeployCommand: |
      # Run database migrations after app is bound to port
      echo "Running post-deployment migrations..."
      flask db upgrade || echo "Migration failed but continuing..."
    healthCheckPath: /health/simple
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SESSION_REDIS_URL
        sync: false
      - key: FLASK_LIMITER_STORAGE_URI
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: GLOBAL_RATE_LIMIT
        value: "120 per minute"
      - key: QUEUE_MODE
        value: celery
      - key: USE_GCS
        value: "1"
      - key: SESSION_TYPE
        value: redis
      - key: SESSION_USE_SIGNER
        value: "true"
      - key: SESSION_KEY_PREFIX
        value: "mdraft:sess:"
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp.json
      - key: GCS_BUCKET_NAME
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_ENVIRONMENT
        value: production
      - key: WEBHOOK_SECRET
        sync: false

  - type: worker
    name: mdraft_app-worker
    env: python
    buildCommand: pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
    runtime: python-3.11.11
    startCommand: celery -A celery_worker.celery worker --loglevel=info --pool=threads --concurrency=2 --without-gossip --without-mingle --without-heartbeat
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: QUEUE_MODE
        value: celery
      - key: USE_GCS
        value: "1"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp.json
      - key: GCS_BUCKET_NAME
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_ENVIRONMENT
        value: production
      - key: WEBHOOK_SECRET
        sync: false

  - type: cron
    name: mdraft-cleanup
    env: python
    schedule: "0 6 * * *"
    buildCommand: pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
    runtime: python-3.11.11
    startCommand: flask --app app:create_app cleanup
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp.json
      - key: GCS_BUCKET_NAME
        sync: false
      - key: CLEANUP_DELETE_GCS
        value: "1"
      - key: RETENTION_DAYS
        value: "30"
      - key: USE_GCS
        value: "1"
