"""Add error_message, started_at, completed_at fields to Job model

Revision ID: 475e4c1d7986
Revises: afbc8388791d
Create Date: 2025-08-10 19:48:17.867103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475e4c1d7986'
down_revision = 'afbc8388791d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'error_message')
    # ### end Alembic commands ###
