"""allowlist_and_user_fields

Revision ID: 926e733b4f22
Revises: e6a1e92a92c3
Create Date: 2025-08-11 20:53:55.597472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926e733b4f22'
down_revision = 'e6a1e92a92c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowlist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowlist_email'), ['email'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revoked', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_email_key', ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('revoked')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('plan')

    with op.batch_alter_table('allowlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowlist_email'))

    op.drop_table('allowlist')
    # ### end Alembic commands ###
