"""add proposal_id to conversions table for relationship to proposals

Revision ID: d4ef9d459d1a
Revises: f54a945227b8
Create Date: 2025-08-14 14:40:29.418067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ef9d459d1a'
down_revision = 'f54a945227b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversions_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_foreign_key('fk_conversions_proposal_id_proposals', 'proposals', ['proposal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversions_proposal_id_proposals', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversions_proposal_id'))
        batch_op.drop_column('proposal_id')

    # ### end Alembic commands ###
