"""ensure progress column exists in conversions table

Revision ID: dfd980eee75b
Revises: 013cba34ee27
Create Date: 2025-08-17 21:32:02.381008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'dfd980eee75b'
down_revision = '013cba34ee27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if progress column already exists
    connection = op.get_bind()
    inspector = inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('conversions')]
    
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        # Only add progress column if it doesn't exist
        if 'progress' not in columns:
            batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
        
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='conversionstatus'),
               existing_nullable=False)
        batch_op.create_index('ix_conversions_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_conversions_status_user_id', ['status', 'user_id'], unique=False)
        batch_op.create_index('ix_conversions_status_visitor_id', ['status', 'visitor_session_id'], unique=False)
        batch_op.create_index('ix_conversions_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_conversions_visitor_id_created_at', ['visitor_session_id', 'created_at'], unique=False)
        batch_op.create_unique_constraint('uq_conversions_sha256_owner', ['sha256', 'user_id', 'visitor_session_id'])

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_email_verification_tokens_user_id')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'),
               existing_nullable=False)

    with op.batch_alter_table('proposal_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_documents_proposal_id')

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_requirements_proposal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index('ix_requirements_proposal_id', ['proposal_id'], unique=False)

    with op.batch_alter_table('proposal_documents', schema=None) as batch_op:
        batch_op.create_index('ix_proposal_documents_proposal_id', ['proposal_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_email_verification_tokens_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_conversions_sha256_owner', type_='unique')
        batch_op.drop_index('ix_conversions_visitor_id_created_at')
        batch_op.drop_index('ix_conversions_user_id_created_at')
        batch_op.drop_index('ix_conversions_status_visitor_id')
        batch_op.drop_index('ix_conversions_status_user_id')
        batch_op.drop_index('ix_conversions_status_created_at')
        batch_op.alter_column('status',
               existing_type=sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='conversionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        # Only drop progress column if it exists
        connection = op.get_bind()
        inspector = inspect(connection)
        columns = [col['name'] for col in inspector.get_columns('conversions')]
        if 'progress' in columns:
            batch_op.drop_column('progress')

    # ### end Alembic commands ###
