"""add ownership fields to conversions table

Revision ID: f54a945227b8
Revises: 3c7eb558ee7d
Create Date: 2025-08-14 13:41:12.868301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54a945227b8'
down_revision = '3c7eb558ee7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visitor_session_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_visitor_session_id'), ['visitor_session_id'], unique=False)
        batch_op.create_foreign_key('fk_conversions_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversions_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversions_visitor_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversions_user_id'))
        batch_op.drop_column('visitor_session_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
