#!/bin/bash
"""
Render Log Checking Script

This script provides guidance on how to check Render logs for the error trap output.
"""

echo "🔍 RENDER LOG CHECKING GUIDE"
echo "============================"
echo ""
echo "Since your error trap is active, you should check the Render logs for:"
echo ""
echo "1. Go to your Render dashboard: https://dashboard.render.com"
echo "2. Click on your 'mdraft-web' service"
echo "3. Click on 'Logs' tab"
echo "4. Look for these specific error messages:"
echo ""
echo "   ❌❌❌ FATAL: Exception occurred during app creation in wsgi.py ❌❌❌"
echo "   ❌❌❌ FATAL: Exception occurred during a request in wsgi.py ❌❌❌"
echo ""
echo "5. Also look for:"
echo "   --- WSGI: Attempting to create Flask app ---"
echo "   --- WSGI: Flask app created successfully ---"
echo "   --- WSGI: Application is wrapped and ready ---"
echo ""
echo "If you see the 'FATAL' messages, copy the full traceback and share it."
echo ""
echo "Common places to find the logs:"
echo "- Build logs (if app creation fails during startup)"
echo "- Runtime logs (if app creation succeeds but requests fail)"
echo "- Health check logs (for startup issues)"
echo ""
echo "To get more detailed logs, you can also run:"
echo "bash scripts/production_debug.sh"
echo ""
echo "This will give you detailed diagnostics about the environment."
